name: Github Actions Example

on:
  pull_request:
  push:

jobs:
  tests:
    name: Running Tests
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      # with:
        # token: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Version
      run: node -v
    - name: Install
      run: npm i
    - name: Test
      run: npm test